version: "3"

services:
  api:
    build:
      context: ./api
    command: gunicorn --reload --bind 0.0.0.0:5000 app.main:app
    ports:
      - "5000:5000"
    volumes:
      - ./api/app:/usr/src/app
    env_file:
      - ./api/.env
    working_dir: /usr/src/app
